### ISSUE TITLE
Packagist package still doesn't support scopes

### ISSUE THREAD

**Issue by ghalse** [cilogon/oauth2-orcid#2]
Some time ago, I submitted pull request #1 to fix the scope separator for ORCID. That request was committed, but there hasn't been a release since. As a result, the package at https://packagist.org/packages/cilogon/oauth2-orcid still doesn't support the correct separator unless I update to dev-master.

Would it be possible to create another release so that I can stop tracking dev-master :-)

**Comment by terrencegf** [comment]
Tagged [1.0.6 release](https://github.com/cilogon/oauth2-orcid/releases/tag/1.0.6).
